### ISSUE TITLE
Plugin has debugging statements left in (calls to error_log)

### ISSUE THREAD

**Issue by jeiseman** [strangerstudios/pmpro-membership-card#15]
The following error_log calls in class.pmpro_posts_by_content.php

`37:        error_log("pmpro_posts_by_content: " . print_r($posts, true));`
`46:        error_log("pmpro_posts_by_content: " . print_r( $where, true ));`
`58:        error_log("pmpro_posts_by_content: " . print_r($new_where, true));`

**Comment by jeiseman** [comment]
Created merge request #16 to fix this issue.

**Comment by andrewlimaza** [comment]
Hi @jeiseman 

Thank you for submitting your PR, we've adjusted this slightly to still log the errors if WP_DEBUG is enabled.

Reference - https://github.com/strangerstudios/pmpro-membership-card/pull/18/files#diff-6f417463d48a02a5c3fbd96222903576R47
