### ISSUE TITLE
The dates and some text requires internatiolization

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-membership-card#17]
Some text, e.g. "Member Since" and "Never", is hard coded in the template and the dates are not internationalized according to the site default language.

- https://github.com/strangerstudios/pmpro-membership-card/blob/2f296ae645c1143e212f22fec91fe060831e30b3/templates/membership-card.php#L90
- https://github.com/strangerstudios/pmpro-membership-card/blob/2f296ae645c1143e212f22fec91fe060831e30b3/templates/membership-card.php#L100
- https://github.com/strangerstudios/pmpro-membership-card/blob/2f296ae645c1143e212f22fec91fe060831e30b3/templates/membership-card.php#L102

We should consider internatiolizing the plugin.

**Comment by andrewlimaza** [comment]
Fixed in latest PR.
