### ISSUE TITLE
Memberlink not working

### ISSUE THREAD

**Issue by abovethefirehouse** [strangerstudios/pmpro-membership-card#2]
I made a page as per the instruction membership-card and added the short code.  I am using pretty permalinks and when I put the mouse over the link to view and print card it shows the wrong page and permalink. How can I fix this? I have latest pmpro and wordpress 4.x
![memcard](https://cloud.githubusercontent.com/assets/9099456/4570325/acd133e0-4f5b-11e4-9e17-4cb33c6b2e61.jpg)
You can see at the bottom its not getting the right permalink.

**Comment by britahahne** [comment]
Yes, this is the same for me, I cant find the problem or where to change it. 
My link goes to: http://www.smpl.nu/blogg/12761-revision-v1/?u=

How do I resolve this error? 

Thanks :)

**Comment by zerotigerds** [comment]
getting same issue

**Comment by mkaobrih** [comment]
I'm getting the same issue. Is it something to do with non default wordpress site installation? My website is mysites/mysite1/wordpress rather than mysite1/wordpress.

**Comment by andrewlimaza** [comment]
I am going to close this issue as this has been fixed previously.
