### ISSUE TITLE
Enhancement: pmpro_membership_card_qr_data_other filter change

### ISSUE THREAD

**Issue by dparker1005** [strangerstudios/pmpro-membership-card#36]
Right now, if you pass a non-default option to `pmpro_membership_card_return_qr_code_data()` and don’t use the `pmpro_membership_card_qr_data_other` filter, then a WP_User object will be passed to `urlencode()` and an error will be thrown.

Ideally, the first param of the `pmpro_membership_card_qr_data_other` filter would be a string to avoid this, maybe `''`.

Relevant code: https://github.com/strangerstudios/pmpro-membership-card/blob/1fc02dbe51ac561b573ba7425a32d4c494721e61/pmpro-membership-card.php#L403-L407

**Comment by andrewlimaza** [comment]
This actually has been fixed in the `dev` branch a while ago, we just need to push it out. Pushing it soon! :)
