### ISSUE TITLE
Update localization to improve translation of text

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-membership-card#38]
Some text strings uses an incorrect text domain
https://github.com/strangerstudios/pmpro-membership-card/blob/a07eff921d4a52c701dbcd5773b36d2f9f06dd57/pmpro-membership-card.php#L250

Some text are hard coded and should be localized.
https://github.com/strangerstudios/pmpro-membership-card/blob/a07eff921d4a52c701dbcd5773b36d2f9f06dd57/pmpro-membership-card.php#L254

**Comment by ipokkel** [comment]
Temporary workaround for "Membership Card" and "View and Print Membership Card" strings:

https://gist.github.com/ipokkel/69b396f29c1e1aa5748be037fc7bc781

**Comment by michaelbeil** [comment]
This came up in ticket 458175, so I suggested the gist.

**Comment by JarrydLong** [comment]
Tested with version 1.1.1 and can confirm that all strings have been localized.
