### ISSUE TITLE
I couldn't add background image on membership card after click on the print option

### ISSUE THREAD

**Issue by ShahriarShaikat** [strangerstudios/pmpro-membership-card#42]
Hello , I am using paid membership pro plugin, i want to customize the membership card .If i put a background color or background image , it is not showing after click on the print option.
![Screenshot_1](https://user-images.githubusercontent.com/65024549/150819644-a296613a-9d49-4b2b-8e2f-4cbfefc20675.png)
![Screenshot_3](https://user-images.githubusercontent.com/65024549/150819659-a8aa6a83-b4e0-459b-9c76-0f442081c6cd.png)
**#here i have change the background image of class .pmpro_membership_card-inner but not showing after click on print!**
![Screenshot_4](https://user-images.githubusercontent.com/65024549/150820121-8a79ee13-3aec-45e5-aa8a-ac54a746171f.png)
![Screenshot_5](https://user-images.githubusercontent.com/65024549/150820134-4a207bcf-2f8f-42fb-8188-b83db642d72e.png)

**Comment by JarrydLong** [comment]
Hi there, 

The printed membership cards make use of different CSS classes - you can check which ones are available in the template under pmpro-membership-card/templates/membership-card.php

Alternatively, you can override the Membership Card template and making additional changes to your membership card from there. A guide on how to do this can be found over at https://www.paidmembershipspro.com/customize-membership-card-wordpress/

Please note that Github is not used monitored for support queries such as the one posted. For further assistance, please reach out to us via our Support Forums (https://www.paidmembershipspro.com/new-topic/)
