### ISSUE TITLE
Print dialog displays multiple duplicate pages

### ISSUE THREAD

**Issue by MaryOJob** [strangerstudios/pmpro-membership-card#48]
To replicate, activate the Membership Card Add-On, add your shortcode to a page, publish, and attempt to print the membership card, the print prompt shows a duplicated page to be printed, instead of displaying only one page.

I deactivated all plugins except PMPro and Membership Card Add-On. I was able to replicate this consistently on my live test site, but not on my local test site.

`
WordPress 6.1.1
PMPro Membership Card 1.1.1
PMPro 2.8.1
Memberlite 4.5.4.1
PHP 8.0.26
`

For moderators only: #470594

**Comment by JarrydLong** [comment]
We've been testing this further but getting inconsistent results (some experience the issue some don't). 

Shortcode used: `[pmpro_membership_card qr_code=”true” qr_data=”email” print_size=”all”]`
Browser used: Chrome in both cases
Tested both on a live site (apache) and a local site (nginx)

The same set of membership card duplicates over multiple pages.

**Comment by andrewlimaza** [comment]
Adding a note here, I'm still unable to replicate this issue but trying to - any information to help us replicate this issue 100% of the time may help us figure out why it's happening.

**Comment by michaelbeil** [comment]
I'm still unable to replicate this issue, but a customer (ticket ID 483978) is experiencing it.

**Comment by michaelbeil** [comment]
I'm unable to replicate this issue, but a customer (ticket ID 483978) is experiencing it.

**Comment by kimcoleman** [comment]
Most likely this is because their theme does not have a print stylesheet set up to exclude other background or site frame elements.
