### ISSUE TITLE
Using the shortcode on a popup returns incorrect information

### ISSUE THREAD

**Issue by metalkakkarot** [strangerstudios/pmpro-membership-card#51]
- I am using elementor pro with the Astra theme.
- I have installed the latest version of paidmembership pro and the membership card plugin
- i have created a new page with the membership pro shortcode pmpro_membership_card.
- i have created a popup with the paidmembershippro shortcode.
- i have created a menu item with a custom link which links to the popup.

This way users who are logged in can access the membership card from both the membership account and from the popup.

**To Reproduce**
1. Click membership popup directly from navigation
2. information returned is 
<img width="317" alt="image" src="https://github.com/strangerstudios/pmpro-membership-card/assets/145217537/d9ac88d8-1792-47dc-97ce-e6a015996d1f">

this is incorrect information.

alternatively:
1. click on my membership
2. click on view membership card (correct information is shown on the page)
3. no click on the same item on the menu bar
4. correct information is returned.

<img width="305" alt="image" src="https://github.com/strangerstudios/pmpro-membership-card/assets/145217537/513dc21c-6fb3-4c61-bd3e-2fc4e4d0bebe">

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [X ] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [? ] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [ X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<current version>
```
Please share non-sensitive information about your hosting environment such as WordPress version, PHP version, Paid Memberships Pro and any related plugins versions.
```
</details>

**Comment by andrewlimaza** [comment]
Hi @metalkakkarot

Does this issue still occur with the latest version of the Membership Card Add On? I am looking into this.

**Comment by andrewlimaza** [comment]
I have retested this and it seems to be working now, with V1.1.3 of the Membership Card Add On. If you still experience issues with this please let me know and I'll continue to look into it further.
